---
title: "Guest Speaker Quiz"
author: "Hannah Levit"
date: "01/11/2021"
output:
  pdf_document: default
  html_document: default
---

## Guest Speaker Quiz

**What you learned from entire speaker series**   
  After all the guest lectures I have a much better grasp on what it is like to be a field ecologist in marine sciences, especially in fisheries science and management. We were lucky to listen to a diverse range of speakers that have different experiences and took different paths to reach their dream jobs. It is good to see what there are people working in the field in a way I am interested in that is beyond academia. There are so many places to work with research and it is a field in which you can combine your passions to make the jobs suit your skill set. The importance of collaboration and networking was also highlighted, it's never going to be only you working by yourself to solve problems and generate new scientific knowledge. I definitely took away that it is important to do what you are passionate about because it is surely not an easy career path (and it's not going to generate considerable wealth).
    I was interested to learn that when studying ecology and biology in general, it's integral to consider how people and communities are involved, and impacted by the ecosystem and the work you're doing. It’s a cyclical relationship that has real world repercussions beyond the specific system or species you are looking at. Dr Calwood's talk on the intersection between fisheries and social science was a great illustration of this in practice. I really enjoy social sciences so it was nice to see someone who was working in a field I'm interested in considering and exploring that in her work. I also found it interesting that the internet has oddly not revolutionized science communication in the way that it has transformed every other aspect of our lives, according to Michael Eisen. Although we have different platforms for communicating science, like great science videos and illustrations available to the public, when it comes to novel research, in order for it to be respected by the scientific community, it must be published in a peer reviewed journal, which is a painfully lengthy process that slows down scientific progress for no reason. 

    
**Three vital pieces of info given to succeed as ecologists?**
  I can surely name more than three pieces of info but the ones that stuck out the most to me were:
  1. Most speakers (namely Sean Godwin and Karlisa Calwood) emphasized the importance of networking and connecting with people that are already doing the things you want to do. As well as making sure your skills are being recognized and you are jumping at opportunities with confidence. Science is not possible without relationships, and building these relationships is sometimes the hardest part of getting where you want to go. It's something you need to practice like all other aspects of science (we even need to practice asking the right questions). Emma Atkinson added that it is good to seek good mentors that work on a diverse range of projects, perhaps things you yourself wouldn't have previously considered. 
  2. Sean Godwin also emphasized the importance of knowing basic programming and modern statistics. Tech literacy is important because it is how we organize and analyze data, as well as how we present it in graphs which are then used to communicate our findings to other researchers and the general public. Emma Atkinson added that it is really good to develop skills both in the field and on the computer, as these compliment each other and allow you to bring more to the table as a scientist. People will simply want to work with you more if you are a jack of all trades instead of a master of one. 
  3. Curiosity is essential when tackling uncertainty - it makes fro more interesting questions, and it is good to feel out of your comfort zone in science. Like a child who is just learning about the world, we should not be afraid to ask what we think are "dumb" questions. It is more than likely that there is some scientist nearby that would be happy to help explain things to you. It is these curious people that are likely to study things that require more creativity, which is essential to science, as Shannon Hennessey discussed. She said that being creative with methods, tools, and analysis can result in more "innovative or interdisciplinary research", it is not always beneficial to stick to traditional methods of research. 
  Additionally, Shannon Hennessey made wonderful science illustrations that helped captivate her audience and are a helpful tool for science communication. Dr. Hennessey also mentioned that observation is key and she clearly uses this in her drawings. 


**What info from lectures are you able to use during the course?**
  Sean Godwin's point about becoming familari with programming helped push me to work harder to understand assignments in this class and to practice using R and github at any opportunity I can. Hence why I am doing this quiz in an R markdown instead of in word, where I would be more comfortable. I enjoyed Shannon Hennessey's talk about the importance of observation, and in this class especially, with all our field work, I try to observe all the natural systems I can and to ask a lot of questions, as that is the best way to learn. I also find that when I draw pictures in my notes it helps me remember topics in class and engage a different part of my brain while learning. Doing such helps me identify where some confusions may be held, and adding colour brings topics and theories to life. I would love to get into scientific illustration in one way or another in my life. Emma Atkinson encouraged getting curious and asking a lot of questions in life and further, in class. It is okay to feel out of your depth and uncomfortable, which I have surely felt more than once in this class. I take pride in the fact that I ask a lot of questions and I am not afraid to sound stupid, so these talks helped encourage that. I also appreciated Dr. Callwood's advice to check our own biases, because science is inherently biased, we bring ourselves to all the work we do, and its better to acknowledge that than ignore it and hope it doesn't impact our research. She also emphasized the importance of forming community and working with and speaking to different people to gain broader perspectives on things you are studying, as well as to provide context, for example in fisheries. I can't just go to a tropical island and assume I know exactly how an ecosystem works without talking to and respecting locals - we need to tackle the distrust in researchers these communities have, for good reason, and work together with them to make both the environment, and their lives, better. 
  Additionally, all speakers encouraged me to work on my science communication skills, which luckily we do a lot of here in Bamfield and especially in this course. I find that I have been getting better at speaking clearly without a script and at getting my point across without using unnecessary jargon. I have also started to work on a website for discussing and displaying my directed studies research, which has been a really fun way to practice different ways of communicating science. I'm using writing, photos, and animation, as a tool to communicate my work with a broad audience (so far only family and friends, but I hope to one day reach more people!). As Emma Atkinson said, "good communication supports good science"! It was also mentioned that getting good at communicating your science helps solidify your own understanding of it, which is true even for course materials. Teaching is the best way to learn!


